# Generated by Django 6.0.4 on 2026-04-16 11:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(db_index=True, max_length=24, unique=True)),
                ("customer_request_text", models.TextField()),
                (
                    "intent",
                    models.CharField(
                        choices=[
                            ("send_money", "send_money"),
                            ("get_airport_transfer", "get_airport_transfer"),
                            ("hire_service", "hire_service"),
                            ("verify_document", "verify_document"),
                            ("check_status", "check_status"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("entities", models.JSONField(blank=True, default=dict)),
                ("risk_score", models.PositiveSmallIntegerField()),
                ("risk_reasons", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=16,
                    ),
                ),
                (
                    "assigned_team",
                    models.CharField(
                        choices=[
                            ("FINANCE", "Finance"),
                            ("OPERATIONS", "Operations"),
                            ("LEGAL", "Legal"),
                            ("SUPPORT", "Support"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TaskEntity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=64)),
                ("value", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_items",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["task", "key"], name="core_tasken_task_id_25408d_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "key", "value"), name="uq_task_entity_kv"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("WHATSAPP", "WhatsApp"),
                            ("EMAIL", "Email"),
                            ("SMS", "SMS"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["task", "channel"],
                        name="core_taskme_task_id_55a63e_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "channel"), name="uq_task_message_channel"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "changed_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "ordering": ["-changed_at"],
                "indexes": [
                    models.Index(
                        fields=["task", "changed_at"],
                        name="core_taskst_task_id_a23a1f_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="TaskStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_order", models.PositiveSmallIntegerField()),
                ("description", models.TextField()),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="core.task",
                    ),
                ),
            ],
            options={
                "ordering": ["task", "step_order"],
                "indexes": [
                    models.Index(
                        fields=["task", "step_order"],
                        name="core_taskst_task_id_6a99d9_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("task", "step_order"), name="uq_task_step_order"
                    )
                ],
            },
        ),
    ]
