# Generated by Django 6.0.4 on 2026-04-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="assignment_reason",
            field=models.TextField(blank=True),
        ),
    ]
